id: 771fdbf4767645be9c1f31d1d8399103
title: Toh_245-The_Sections_of_Dharma-v2
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-066-003
  eft-text-version: 1.1.1 2019
